<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>欢迎来到SpringSecurity的世界</title>
</head>
<body>
欢迎来到SpringSecurity的世界!<br />
<table>
    <tr>
        <td>用户ID</td>
        <td>姓名</td>
        <td>年龄</td>
    </tr>
    <tr>
        <td>1</td>
        <td>张三</td>
        <td>王五</td>
    </tr>
    <tr>
        <td>2</td>
        <td>张三2</td>
        <td>王五</td>
    </tr>
    <tr>
        <td>3</td>
        <td>张三3</td>
        <td>王五</td>
    </tr>
    <tr>
        <td>4</td>
        <td>张三4</td>
        <td>王五</td>
    </tr>
</table>
</body>
</html>